### ISSUE TITLE
./battery-test.sh asking for password

### ISSUE THREAD

**Issue by userow** [geerlingguy/macbook-pro-battery-test#11]
battery-test.sh keep asking for password while it's executing

OSX 10.13.5

anually adding equivalent entries to the hosts file.
Password:

==> macbook_pro_battery_test: [vagrant-hostsupdater] Removing hosts
Password:

**Comment by geerlingguy** [comment]
So, there are two options for getting past this:

  1. Uninstall the `vagrant-hostsupdater` plugin.
  2. Modify your `/etc/sudoers` file to allow Vagrant to write to /etc/hosts without a password required; see: https://www.jeffgeerling.com/blogs/jeff-geerling/better-vagrant-development-workflow
